name          'puppet-sickbeard'
version       '0.0.1'
source        'https://github.com/DexterTheDragon/puppet-sickbeard'
author        'DexterTheDragon'
license       'Apache License, Version 2.0'
summary       'Module to install sickbeard'
description   'Installs and configures sickbeard'
project_page  'https://github.com/DexterTheDragon/puppet-sickbeard'

dependency 'puppetlabs/stdlib', '>= 0'
dependency 'puppetlabs/vcsrepo', '>= 0'
